name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{"id": "common-libraries", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}"}]'

      - name: Publish to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PER_GITHUB_TOKEN }}
        run: mvn deploy -DskipTests

  update-jira:
    name: Update Jira Status
    needs: [ publish ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Branch Name & Update Jira
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          BRANCH_NAME=$(gh pr list --search "${{ github.sha }}" --state merged --json headRefName --jq '.[0].headRefName')
          
          if [ -z "$BRANCH_NAME" ] || [ "$BRANCH_NAME" == "null" ]; then
            PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '#\d+' | head -n 1 | tr -d '#')
            if [ ! -z "$PR_NUMBER" ]; then
              BRANCH_NAME=$(gh pr view "$PR_NUMBER" --json headRefName --jq '.headRefName')
            fi
          fi
          
          if [ -z "$BRANCH_NAME" ] || [ "$BRANCH_NAME" == "null" ]; then
            echo "Không xác định được tên nhánh từ commit này (Không phải PR). Bỏ qua cập nhật Jira."
            exit 0
          fi
          
          echo "Nhánh gốc của PR là: $BRANCH_NAME"
          
          ISSUE_KEY=$(echo "$BRANCH_NAME" | grep -oP '[A-Z]+-\d+' | head -n 1)
          
          if [ -z "$ISSUE_KEY" ]; then
            echo "Không tìm thấy mã Jira trong tên nhánh. Bỏ qua."
            exit 0
          fi
          
          echo "Đã tìm thấy task $ISSUE_KEY. Bắt đầu gọi API Jira..."
          
          TRANSITION_ID="7" 
          
          curl --request POST \
            --url "https://$JIRA_DOMAIN/rest/api/3/issue/$ISSUE_KEY/transitions" \
            --user "$JIRA_EMAIL:$JIRA_TOKEN" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "transition": {
                "id": "'"$TRANSITION_ID"'"
              }
            }' -w "\nHTTP Status: %{http_code}\n"